### ISSUE TITLE
go generate gives missing go sum entry for module errors

### ISSUE THREAD

**Issue by peter9207** [99designs/gqlgen#1483] opened 2021-03-10 08:00 UTC
### What happened?

running `go generate ./...` 
gives go package errors
```
../../../../../go/pkg/mod/github.com/99designs/gqlgen@v0.13.0/cmd/gen.go:9:2: missing go.sum entry for module providing package github.com/urfave/cli/v2
../../../../../go/pkg/mod/github.com/99designs/gqlgen@v0.13.0/internal/imports/prune.go:15:2: missing go.sum entry for module providing package golang.org/x/tools/go/ast/astutil
../../../../../go/pkg/mod/github.com/99designs/gqlgen@v0.13.0/internal/code/packages.go:8:2: missing go.sum entry for module providing package golang.org/x/tools/go/packages
../../../../../go/pkg/mod/github.com/99designs/gqlgen@v0.13.0/internal/imports/prune.go:16:2: missing go.sum entry for module providing package golang.org/x/tools/imports
graph/resolver.go:3: running "go": exit status 1
```

if i run `go get` on each of these dependencies the error goes away and i can generate files just fine, but they come back after 1-2 days. so its quite annoying to keep having to run these.

I've spoken to a couple of people who used gqlgen before and none of them had any problems so I'm sure its not a super big deal. But just looking to get some help to get rid of these errors.

### What did you expect?
go generate to generate the files without these errors
### Minimal graphql.schema and models to reproduce
this happens with even the default generated schema
### versions
 - `gqlgen version`? v0.13.0
 - `go version`?  go1.16beta1 darwin/arm64
 - dep or go modules? go modules

**Comment by jaanreinok** [comment] 2021-03-10 13:48
In my case I get next error in gitlab runner:
`../.cache/pkg/mod/github.com/99designs/gqlgen@v0.13.0/cmd/gen.go:9:2: missing go.sum entry for module providing package github.com/urfave/cli/v2 (imported by github.com/99designs/gqlgen/cmd); to add:
	go get github.com/99designs/gqlgen/cmd@v0.13.0`
What I have done without any results:
cleaned gitlab runner cache. Upped version gqlgen version, ran go mod tidy.  
go 15

**Comment by peter9207** [comment] 2021-03-11 02:53
upon further debugging it seems that when i manually run `go get` it adds them to my go.mod file. which is why the error disappears. but when i run `go mod tidy` it cleans up these dependencies cuz i dont use them anywhere. and i get the error again.

**Comment by jaanreinok** [comment] 2021-03-13 19:58
In my gitlab ci i fixed build issue like this. Second line might not be relevant for you.
```
- go get github.com/99designs/gqlgen/cmd@v0.13.0 && go run github.com/99designs/gqlgen
- go run github.com/markbates/pkger/cmd/pkger
```

**Comment by rokjoana** [comment] 2021-03-23 12:01
I'm experiencing the same problem with g1.16. I usually run via `go run github.com/99designs/gqlgen generate` and it gives me with the same error with version 0.12.2
```
../../go/pkg/mod/github.com/99designs/gqlgen@v0.12.2/cmd/gen.go:9:2: missing go.sum entry for module providing package github.com/urfave/cli/v2 (imported by github.com/99designs/gqlgen/cmd); to add:
        go get github.com/99designs/gqlgen/cmd@v0.12.2
```

**Comment by JonasDoe** [comment] 2021-04-19 09:43
I figure that's a general bug in Go 1.16: https://github.com/golang/go/issues/44129 - I have troubles with other dependencies, too.

**Comment by Matts966** [comment] 2021-06-19 20:11
@JonasDoe @peter9207 
Thank you for tracking. This may be resolved by closed by https://github.com/golang/go/issues/44129#issuecomment-854975677.

**Comment by quangthe** [comment] 2021-09-09 05:11
> I figure that's a general bug in Go 1.16: [golang/go#44129](https://github.com/golang/go/issues/44129) - I have troubles with other dependencies, too.

I used Go 1.17 and have the same issue.

**Comment by altanozlu** [comment] 2021-09-09 14:40
Same with go 1.17

**Comment by altanozlu** [comment] 2021-09-09 14:47
Deleting go.sum fixed it.

**Comment by avi94** [comment] 2021-10-06 08:06
Same issue here by the way, using gqlgen version 0.14.0, and Go version 1.17. No matter what, none of the solutions mentioned above work. Completely confused as to what the issue is!

Any help would be greatly appreciated!

**Comment by juddbaguio** [comment] 2021-10-07 23:52
Same issue here.

**Comment by uid-one** [comment] 2021-10-18 07:44
I fixed with "go get -u github.com/99designs/gqlgen/cmd"

**Comment by Vovcharaa** [comment] 2021-10-21 21:38
After every run of `go generate ./...` I need to run `go get -d github.com/99designs/gqlgen` to fix this issue.
Adding `//go:generate go get -d github.com/99designs/gqlgen` before `//go:generate go run github.com/99designs/gqlgen` seems to work fine.

**Comment by peteole** [comment] 2021-11-08 08:18
Actually this from the introduction page fixed it for me, even though I did not have the time to find out what it's actually doing:

```
printf '// +build tools\npackage tools\nimport _ "github.com/99designs/gqlgen"' | gofmt > tools.go
go mod tidy
```

**Comment by frederikhors** [comment] 2022-03-02 09:05
Can we close this? @mtibben @peteole?

**Comment by Diabolarius** [comment] 2022-03-06 10:50
Actually, I believe not. All here is just workarounds. The problem seems in the generate script and the package handling of gqlgen itself rooted. 
The reference of the packages seems not to be correct in gqlgen, therefore the generate execution/mod tidy removes these three packages each time during generation. Therefore they need to be installed/added manually or semi-automatically each time before the generation can run. This is not intended behavior. The referencing of the packages should be cleaned up, so the packages remain in the go.sum after gqlgen generate was executed.

**Comment by frederikhors** [comment] 2022-03-06 11:15
@Diabolarius what you're saying is not on my projects. Can you create a repro? I'll be happy to help you.

**Comment by frederikhors** [comment] 2022-03-12 17:23
Please write here if the problem persists.

**Closed by frederikhors** 2022-03-12 17:23 UTC

**Comment by kateile** [comment] 2022-03-21 02:48
This works for me though I don't know how
```
go run -mod=mod github.com/99designs/gqlgen generate
```

**Comment by iamchubko** [comment] 2022-03-21 12:27
> This works for me though I don't know what it does
> 
> ```
> go run -mod=mod github.com/99designs/gqlgen generate
> ```

[https://go.dev/ref/mod](https://go.dev/ref/mod#:~:text=The%20%2Dmod%3Dmod%20flag%20instructs%20the%20go%20command%20to%20attempt%20to%20find%20new%20modules%20providing%20missing%20packages%20and%20to%20update%20go.mod%20and%20go.sum.%20The%20go%20get%20and%20go%20mod%20tidy%20commands%20do%20this%20automatically.)

> The -mod=mod flag instructs the go command to attempt to find new modules providing missing packages and to update go.mod and go.sum. The [go get](https://go.dev/ref/mod#go-get) and [go mod tidy](https://go.dev/ref/mod#go-mod-tidy) commands do this automatically.

And yeah, it helped me, too

**Comment by juanjoseluisgarcia** [comment] 2024-06-18 15:02
> This works for me though I don't know what it does
> 
> ```
> go run -mod=mod github.com/99designs/gqlgen generate
> ```

THIS IS THE ANSWER. Without this the packet do not work
