### ISSUE TITLE
Golang Lru type parameter requires go1.18 or later

### ISSUE THREAD

**Issue by crcortesd** [99designs/gqlgen#2576] opened 2023-03-03 02:45 UTC
### What happened?

Hi, i just tried installing the library and after running `go run ./server.go` im getting the following errors

`../pkg/mod/github.com/hashicorp/golang-lru/v2@v2.0.1/simplelru/list.go:8:12: type parameter requires go1.18 or later (-lang was set to go1.16; check go.mod)`
`../pkg/mod/github.com/hashicorp/golang-lru/v2@v2.0.1/simplelru/list.go:8:14: predeclared comparable requires go1.18 or later (-lang was set to go1.16; check go.mod)`
`../pkg/mod/github.com/hashicorp/golang-lru/v2@v2.0.1/simplelru/list.go:8:28: predeclared any requires go1.18 or later (-lang was set to go1.16; check go.mod)`
`../pkg/mod/github.com/hashicorp/golang-lru/v2@v2.0.1/simplelru/list.go:14:19: type instantiation requires go1.18 or later (-lang was set to go1.16; check go.mod)`

and so on, until im getting the too many errors message

I got it to work by reversing #2570 update though

### versions
 - `v0.17.25`?
 - `go version go1.20.1 darwin/amd64`?

**Comment by StevenACoffman** [comment] 2023-03-10 02:06
I suspect you need a `go.mod` file in the place where your `server.go` file is located, and it should specify Go 1.18.

As of the Go 1.17 release, if the [go directive](https://go.dev/ref/mod#go-mod-file-go) is missing, go 1.16 is assumed

**Comment by StevenACoffman** [comment] 2023-03-10 02:21
I cannot otherwise reproduce this problem on darwin/amd64 with Go 1.20.1, so I'm going to close this issue for now.

**Closed by StevenACoffman** 2023-03-10 02:21 UTC

**Comment by cdavis09** [comment] 2023-03-17 00:11
I am still seeing this issue. Testing with 1.18.10, 1.19.7 and 1.20.2.

I can also confirm that after removing https://github.com/99designs/gqlgen/pull/2570 it works with all 3.

**Comment by StevenACoffman** [comment] 2023-03-17 01:42
@cdavis09 I suspect your problem is caused by you running `go run ./server.go` in a directory without a `go.mod` file. If so, you need to run something like:
```
go mod init github.com/cdavis09/mygraph
go mod tidy
go run ./server.go
```

This would most likely solve what I imagine your problem is. If not, Can you provide a repository that demonstrates this issue? I am not able to reproduce it.

**Comment by cdavis09** [comment] 2023-03-17 17:15
Hi @StevenACoffman, I did exactly as you suggested above. I initialized a clean project (e.g. `go mod init ...`) and followed the directions in the README to initialize `gqlgen`. I had the exact same issue for all 3 versions of go that I listed - tested just so I could say I did. 

The only way to get it to run was by pulling a local copy of `gqlgen`, from version `v0.17.26` and reverting the commit for https://github.com/99designs/gqlgen/pull/2570 and then forcing my local projects to use the local module for `gqlgen`. 

Note that I tried it 2 ways once I established that it worked. I completely initialized a project using latest `gqlgen` to the point of running `go run ./server.go` and seeing the above errors. Then I replaced the dependency using my local copy. Go correctly complained about the version of the `github.com/hashicorp/golang-lru ` dependency and once I got the `go.sum` for the earlier version reran it and it compiled and ran fine.

**Comment by StevenACoffman** [comment] 2023-03-18 14:48
Hey, thanks very much for doing all that and clarifying, and I'm really sorry for this. I have to admit I'm somewhat stymied by not being able to reproduce this problem locally. Thanks for continuing to stick with it.

When you initialized a clean project with `go mod init github.com/cdavis09/mygraph` the `go.mod` file it creates has `go 1.18` in it or `go 1.16`?

Can you also tell me what the output of `go env` is for you?

**Comment by cdavis09** [comment] 2023-04-04 01:50
I wanted to update that this is still an issue, at least when following the directions directly. After looking into it a little more (there's still some things going on I haven't had time to track down) I found a simple workaround. 

With all of the above reported environment and versions the same, I can reproduce the failure 100% of the time. I looked into the cache and path resolution for the dependency on `simplelru` (from `hashicorp/golang-lru`), noting that `GOPATH` and cached versions still contained their respective `go.mod` files indicating `go1.18` as expected.

But, if after running `go run github.com/99designs/gqlgen init` I ran `go mod tidy` _again_, it resolved the issue.  Here's the diff from my `go.mod` file before and after running the extra `go mod tidy`

```
5c5,8
< require github.com/99designs/gqlgen v0.17.28
---
> require (
>       github.com/99designs/gqlgen v0.17.28
>       github.com/vektah/gqlparser/v2 v2.5.1
> )
9a13,15
>       github.com/gorilla/websocket v1.5.0 // indirect
>       github.com/hashicorp/golang-lru/v2 v2.0.1 // indirect
>       github.com/mitchellh/mapstructure v1.5.0 // indirect
12d17
<       github.com/vektah/gqlparser/v2 v2.5.1 // indirect
```

As you can see, it moved `gqlparser` alongside `gqlgen` in the separate "direct dependency" block and added an indirect entry for `golang-lru`, `websocket` and `mapstructure`. By bringing in `golang-lru` suddenly - the error goes away and it compiles and runs just fine.

And glancing at the binary (using `go build` instead of `go run`) we can see it compiled the correct versions of the dependencies.

```
go version -m server
server: go1.20.2
	path	command-line-arguments
	dep	github.com/99designs/gqlgen	v0.17.28	h1:kbc1RhvwMltFVCb6drIrfQcxS9iKybyNwaJkgJZd5ao=
	dep	github.com/agnivade/levenshtein	v1.1.1	h1:QY8M92nrzkmr798gCo3kmMyqXFzdQVpxLlGPRBij0P8=

	dep	github.com/gorilla/websocket	v1.5.0	h1:PPwGk2jz7EePpoHN/+ClbZu8SPxiqlu12wZP/3sWmnc=
	dep	github.com/hashicorp/golang-lru/v2	v2.0.1	h1:5pv5N1lT1fjLg2VQ5KWc7kmucp2x/kvFOnxuVTqZ6x4=
	dep	github.com/mitchellh/mapstructure	v1.5.0	h1:jeMsZIYE/09sWLaz43PL7Gy6RuMjD2eJVyuac5Z2hdY=
	dep	github.com/vektah/gqlparser/v2	v2.5.1	h1:ZGu+bquAY23jsxDRcYpWjttRZrUz07LbiY77gUOHcr4=
```

I don't know why this wasn't necessary before or why it's not necessary when you (@StevenACoffman) run the instructions in the `README.md` file or the docs tutorial, but this is where I'm at.

**Comment by StevenACoffman** [comment] 2023-04-04 21:08
Oh wow. Ok, thanks.

So gqlgen generate currently runs Go mod tidy here: https://github.com/99designs/gqlgen/blob/1c6bf9bd7426ab68c73e4955d0896833cad0e415/api/generate.go#L100

Is it possible the config file sets `SkipModTidy` to true?

**Comment by cdavis09** [comment] 2023-04-07 23:13
Hi Steven, no the config file does not set that value. I have been using the default file generated from the `init` command.
