### ISSUE TITLE
Generation error on Go 1.22.0

### ISSUE THREAD

**Issue by fresonn** [99designs/gqlgen#2895] opened 2024-02-07 12:42 UTC
### What happened?
I reproduced all steps from ["Getting Started"](https://gqlgen.com/getting-started/) guide before next line
```bash
go run github.com/99designs/gqlgen init
Creating gqlgen.yml
Creating graph/schema.graphqls
Creating server.go
Generating...
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1077863be]
```
Very unusual behavior, I tried to update gqlgen to the new version on the main project, but I see that this problem is also reproduced in the "Getting Started" sandbox

### What did you expect?
Normal generation operation

### Minimal graphql.schema and models to reproduce
nil 🙃
### versions
 - `go run github.com/99designs/gqlgen version` --> v0.17.43
 - `go version` --> go1.22.0 darwin/amd64

**Comment by cyrilc-pro** [comment] 2024-02-07 13:07
Having the same issue, I was able to workaround it by using `github.com/99designs/gqlgen v0.17.44-0.20240130005934-e174d59ed2da`.

**Comment by cyrilc-pro** [comment] 2024-02-07 15:29
I also had to upgrade all my dependencies in the `go.mod` (not sure which ones helped solving the issue)

**Comment by randallmlough** [comment] 2024-02-08 16:41
Same experience – worth noting I also had the same issues with the RC's too. Had to downgrade Go 1.21 for now

**Comment by fresonn** [comment] 2024-02-12 10:41
I found temporary solution.
1. rm -r graph gqlgen.yml go.sum 
2. go mod tidy
3. go get -u  github.com/99designs/gqlgen

Then run `go run github.com/99designs/gqlgen init`
its produce next output
```bash
Creating gqlgen.yml
Creating graph/schema.graphqls
Creating server.go
Generating...

Exec "go run ./server.go" to start GraphQL server
```
If you have already existed schema and gql server:
`go run github.com/99designs/gqlgen generate` works fine to

**Comment by werjo** [comment] 2024-02-12 11:58
the solution is not working for us. There is still a panic. But only on go sources. So maybe its a bug in go and not at graphqlgen (last stable release `v0.17.43`

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x100c5c110]

goroutine 64 [running]:
go/types.(*Checker).handleBailout(0x140005e6000, 0x1400020fb98)
        /usr/local/go/src/go/types/check.go:367 +0x9c
panic({0x100f4c0e0?, 0x101275180?})
        /usr/local/go/src/runtime/panic.go:770 +0x124
go/types.(*StdSizes).Sizeof(0x0, {0x100fbf920, 0x10127b220})
        /usr/local/go/src/go/types/sizes.go:228 +0x320
go/types.(*Config).sizeof(...)
        /usr/local/go/src/go/types/sizes.go:333
go/types.representableConst.func1({0x100fbf920?, 0x10127b220?})
        /usr/local/go/src/go/types/const.go:76 +0x9c
go/types.representableConst({0x100fc1e58, 0x10129d220}, 0x140005e6000, 0x10127b220, 0x1400020e798)
        /usr/local/go/src/go/types/const.go:92 +0x138
go/types.(*Checker).representation(0x140005e6000, 0x1400054e680, 0x10127b220)
        /usr/local/go/src/go/types/const.go:256 +0x68
go/types.(*Checker).implicitTypeAndValue(0x140005e6000, 0x1400054e680, {0x100fbf920, 0x10127b220})
        /usr/local/go/src/go/types/expr.go:375 +0x340
go/types.(*Checker).assignment(0x140005e6000, 0x1400054e680, {0x100fbf920, 0x10127b220}, {0x100e16129, 0x10})
        /usr/local/go/src/go/types/assignments.go:52 +0x23c
go/types.(*Checker).initVar(0x140005e6000, 0x1400062de00, 0x1400054e680, {0x100e16129, 0x10})
        /usr/local/go/src/go/types/assignments.go:163 +0x39c
go/types.(*Checker).initVars(0x140005e6000, {0x14000326108, 0x1, 0x100c6c7dc?}, {0x1400059e130, 0x100c6c720?, 0x140005d4cf8?}, {0x100fc0ec8, 0x140005aa6e0?})
        /usr/local/go/src/go/types/assignments.go:382 +0x588
go/types.(*Checker).stmt(0x140005e6000, 0x0, {0x100fc0ec8, 0x140005aa6e0})
        /usr/local/go/src/go/types/stmt.go:524 +0x18a4
go/types.(*Checker).stmtList(0x140005e6000, 0x0, {0x1400059e140?, 0x0?, 0x0?})
        /usr/local/go/src/go/types/stmt.go:121 +0x88
go/types.(*Checker).funcBody(0x140005e6000, 0x100fbf920?, {0x14000590254?, 0x10127b220?}, 0x1400054e600, 0x140005a4690, {0x0?, 0x0?})
        /usr/local/go/src/go/types/stmt.go:41 +0x21c
go/types.(*Checker).funcDecl.func1()
        /usr/local/go/src/go/types/decl.go:852 +0x44
go/types.(*Checker).processDelayed(0x140005e6000, 0x0)
        /usr/local/go/src/go/types/check.go:467 +0x12c
go/types.(*Checker).checkFiles(0x140005e6000, {0x14000036060, 0x2, 0x2})
        /usr/local/go/src/go/types/check.go:411 +0x188
go/types.(*Checker).Files(...)
        /usr/local/go/src/go/types/check.go:372
golang.org/x/tools/go/packages.(*loader).loadPackage(0x14000264380, 0x140000b3ce0)
        /Users/joerg.werner/Go/pkg/mod/golang.org/x/tools@v0.9.3/go/packages/packages.go:1055 +0x870
golang.org/x/tools/go/packages.(*loader).loadRecursive.func1()
        /Users/joerg.werner/Go/pkg/mod/golang.org/x/tools@v0.9.3/go/packages/packages.go:854 +0x178
sync.(*Once).doSlow(0x0?, 0x0?)
        /usr/local/go/src/sync/once.go:74 +0x100
sync.(*Once).Do(...)
        /usr/local/go/src/sync/once.go:65
golang.org/x/tools/go/packages.(*loader).loadRecursive(0x0?, 0x0?)
        /Users/joerg.werner/Go/pkg/mod/golang.org/x/tools@v0.9.3/go/packages/packages.go:842 +0x50
golang.org/x/tools/go/packages.(*loader).loadRecursive.func1.1(0x0?)
        /Users/joerg.werner/Go/pkg/mod/golang.org/x/tools@v0.9.3/go/packages/packages.go:849 +0x30
created by golang.org/x/tools/go/packages.(*loader).loadRecursive.func1 in goroutine 60
        /Users/joerg.werner/Go/pkg/mod/golang.org/x/tools@v0.9.3/go/packages/packages.go:848 +0x84
exit status 2
```

**Comment by fresonn** [comment] 2024-02-12 12:18
@werjo no it's not a golang compiler bug.
I reproduce these steps in sandbox and main project and it works on both...

Try to `rm go.sum && go get -u github.com/99designs/gqlgen` and then `go run github.com/99designs/gqlgen generate`

**Comment by werjo** [comment] 2024-02-12 13:58
Maybe its a MAC (arm) problem:

Just started a brand new module (nothing special):

schema.graphql:

```graphql
type Test {
    id: String!
    value: Float!
}

type Query {
    getTests: [Test!]!
}
```
gqlgen.yml

```yaml
exec:
  filename: generated/exec.go
model:
  filename: models/generated.go
  package: models

autobind:
  - test/models
```

an empty models.go in the dir models (to have the package)

go.mod
```
module test

go 1.22
```

```sh
go get github.com/99designs/gqlgen
go run github.com/99designs/gqlgen@latest generate --config gqlgen.yml
```

->

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x104828110]

goroutine 423 [running]:
go/types.(*Checker).handleBailout(0x140004d2000, 0x140002b3b98)
        /usr/local/go/src/go/types/check.go:367 +0x9c
panic({0x104b180e0?, 0x104e41180?})
        /usr/local/go/src/runtime/panic.go:770 +0x124
go/types.(*StdSizes).Sizeof(0x0, {0x104b8b920, 0x104e47220})
        /usr/local/go/src/go/types/sizes.go:228 +0x320
go/types.(*Config).sizeof(...)
        /usr/local/go/src/go/types/sizes.go:333
go/types.representableConst.func1({0x104b8b920?, 0x104e47220?})
        /usr/local/go/src/go/types/const.go:76 +0x9c
go/types.representableConst({0x104b8de58, 0x104e69220}, 0x140004d2000, 0x104e47220, 0x140002afb88)
        /usr/local/go/src/go/types/const.go:92 +0x138
go/types.(*Checker).representation(0x140004d2000, 0x140003a1240, 0x104e47220)
        /usr/local/go/src/go/types/const.go:256 +0x68
go/types.(*Checker).implicitTypeAndValue(0x140004d2000, 0x140003a1240, {0x104b8b920, 0x104e47220})
        /usr/local/go/src/go/types/expr.go:375 +0x340
go/types.(*Checker).convertUntyped(0x140004d2000, 0x140003a1240, {0x104b8b920, 0x104e47220})
        /usr/local/go/src/go/types/const.go:289 +0x30
go/types.(*Checker).matchTypes(0x140004d2000, 0x140003a1140, 0x140003a1240)
        /usr/local/go/src/go/types/expr.go:926 +0x7c
go/types.(*Checker).binary(0x140004d2000, 0x140003a1140, {0x104b8cb98, 0x14000356570}, {0x104b8d288, 0x14000784380}, {0x104b8d168, 0x140007830a0}, 0x29, 0x393be)
        /usr/local/go/src/go/types/expr.go:800 +0x114
go/types.(*Checker).exprInternal(0x140004d2000, 0x0, 0x140003a1140, {0x104b8cb98, 0x14000356570}, {0x0, 0x0})
        /usr/local/go/src/go/types/expr.go:1416 +0x1d4
go/types.(*Checker).rawExpr(0x140004d2000, 0x0, 0x140003a1140, {0x104b8cb98?, 0x14000356570?}, {0x0?, 0x0?}, 0x0)
        /usr/local/go/src/go/types/expr.go:979 +0x12c
go/types.(*Checker).expr(0x140004d2000, 0x1047d3a84?, 0x140003a1140, {0x104b8cb98?, 0x14000356570?})
        /usr/local/go/src/go/types/expr.go:1513 +0x38
go/types.(*Checker).binary(0x140004d2000, 0x140003a1140, {0x104b8cb98, 0x140003565d0}, {0x104b8cb98, 0x14000356570}, {0x104b8cb98, 0x140003565a0}, 0x22, 0x393c2)
        /usr/local/go/src/go/types/expr.go:783 +0x70
go/types.(*Checker).exprInternal(0x140004d2000, 0x0, 0x140003a1140, {0x104b8cb98, 0x140003565d0}, {0x0, 0x0})
        /usr/local/go/src/go/types/expr.go:1416 +0x1d4
go/types.(*Checker).rawExpr(0x140004d2000, 0x0, 0x140003a1140, {0x104b8cb98?, 0x140003565d0?}, {0x0?, 0x0?}, 0x0)
        /usr/local/go/src/go/types/expr.go:979 +0x12c
go/types.(*Checker).expr(0x140004d2000, 0x0?, 0x140003a1140, {0x104b8cb98?, 0x140003565d0?})
        /usr/local/go/src/go/types/expr.go:1513 +0x38
go/types.(*Checker).binary(0x140004d2000, 0x140003a1140, {0x104b8cb98, 0x140006740c0}, {0x104b8cb98, 0x140003565d0}, {0x104b8cb98, 0x14000674090}, 0x22, 0x393d0)
        /usr/local/go/src/go/types/expr.go:783 +0x70
go/types.(*Checker).exprInternal(0x140004d2000, 0x0, 0x140003a1140, {0x104b8cb98, 0x140006740c0}, {0x0, 0x0})
        /usr/local/go/src/go/types/expr.go:1416 +0x1d4
go/types.(*Checker).rawExpr(0x140004d2000, 0x0, 0x140003a1140, {0x104b8cb98?, 0x140006740c0?}, {0x0?, 0x0?}, 0x0)
        /usr/local/go/src/go/types/expr.go:979 +0x12c
go/types.(*Checker).expr(0x140004d2000, 0xffff?, 0x140003a1140, {0x104b8cb98?, 0x140006740c0?})
        /usr/local/go/src/go/types/expr.go:1513 +0x38
go/types.(*Checker).binary(0x140004d2000, 0x140003a1140, {0x104b8cb98, 0x140006741b0}, {0x104b8cb98, 0x140006740c0}, {0x104b8cb98, 0x14000674180}, 0x22, 0x3941d)
        /usr/local/go/src/go/types/expr.go:783 +0x70
go/types.(*Checker).exprInternal(0x140004d2000, 0x0, 0x140003a1140, {0x104b8cb98, 0x140006741b0}, {0x0, 0x0})
        /usr/local/go/src/go/types/expr.go:1416 +0x1d4
go/types.(*Checker).rawExpr(0x140004d2000, 0x0, 0x140003a1140, {0x104b8cb98?, 0x140006741b0?}, {0x0?, 0x0?}, 0x0)
        /usr/local/go/src/go/types/expr.go:979 +0x12c
go/types.(*Checker).expr(0x140004d2000, 0x104e47200?, 0x140003a1140, {0x104b8cb98?, 0x140006741b0?})
        /usr/local/go/src/go/types/expr.go:1513 +0x38
go/types.(*Checker).initVars(0x140004d2000, {0x140005b0040, 0x1, 0x1048387dc?}, {0x14000698380, 0x104838720?, 0x1400072ccf8?}, {0x104b8cec8, 0x1400007a640?})
        /usr/local/go/src/go/types/assignments.go:381 +0x570
go/types.(*Checker).stmt(0x140004d2000, 0x0, {0x104b8cec8, 0x1400007a640})
        /usr/local/go/src/go/types/stmt.go:524 +0x18a4
go/types.(*Checker).stmtList(0x140004d2000, 0x0, {0x14000698390?, 0x0?, 0x0?})
        /usr/local/go/src/go/types/stmt.go:121 +0x88
go/types.(*Checker).funcBody(0x140004d2000, 0x104b8b920?, {0x140000cc510?, 0x104e47200?}, 0x140003a0000, 0x140006741e0, {0x0?, 0x0?})
        /usr/local/go/src/go/types/stmt.go:41 +0x21c
go/types.(*Checker).funcDecl.func1()
        /usr/local/go/src/go/types/decl.go:852 +0x44
go/types.(*Checker).processDelayed(0x140004d2000, 0x0)
        /usr/local/go/src/go/types/check.go:467 +0x12c
go/types.(*Checker).checkFiles(0x140004d2000, {0x140001a4060, 0x1, 0x1})
        /usr/local/go/src/go/types/check.go:411 +0x188
go/types.(*Checker).Files(...)
        /usr/local/go/src/go/types/check.go:372
golang.org/x/tools/go/packages.(*loader).loadPackage(0x140001e4540, 0x14000247cb0)
        /Users/joerg.werner/Go/pkg/mod/golang.org/x/tools@v0.9.3/go/packages/packages.go:1055 +0x870
golang.org/x/tools/go/packages.(*loader).loadRecursive.func1()
        /Users/joerg.werner/Go/pkg/mod/golang.org/x/tools@v0.9.3/go/packages/packages.go:854 +0x178
sync.(*Once).doSlow(0x0?, 0x0?)
        /usr/local/go/src/sync/once.go:74 +0x100
sync.(*Once).Do(...)
        /usr/local/go/src/sync/once.go:65
golang.org/x/tools/go/packages.(*loader).loadRecursive(0x0?, 0x0?)
        /Users/joerg.werner/Go/pkg/mod/golang.org/x/tools@v0.9.3/go/packages/packages.go:842 +0x50
golang.org/x/tools/go/packages.(*loader).loadRecursive.func1.1(0x0?)
        /Users/joerg.werner/Go/pkg/mod/golang.org/x/tools@v0.9.3/go/packages/packages.go:849 +0x30
created by golang.org/x/tools/go/packages.(*loader).loadRecursive.func1 in goroutine 418
        /Users/joerg.werner/Go/pkg/mod/golang.org/x/tools@v0.9.3/go/packages/packages.go:848 +0x84
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x104828110]

goroutine 256 [running]:
go/types.(*Checker).handleBailout(0x140003a6600, 0x140002bfb98)
        /usr/local/go/src/go/types/check.go:367 +0x9c
panic({0x104b180e0?, 0x104e41180?})
        /usr/local/go/src/runtime/panic.go:770 +0x124
go/types.(*StdSizes).Sizeof(0x0, {0x104b8b920, 0x104e472c0})
        /usr/local/go/src/go/types/sizes.go:228 +0x320
go/types.(*Config).sizeof(...)
        /usr/local/go/src/go/types/sizes.go:333
go/types.representableConst.func1({0x104b8b920?, 0x104e472c0?})
        /usr/local/go/src/go/types/const.go:76 +0x9c
go/types.representableConst({0x104b8de58, 0x104e69270}, 0x140003a6600, 0x104e472c0, 0x140002badb8)
        /usr/local/go/src/go/types/const.go:106 +0x2b0
go/types.(*Checker).representation(0x140003a6600, 0x140006c6ac0, 0x104e472c0)
        /usr/local/go/src/go/types/const.go:256 +0x68
go/types.(*Checker).representable(0x140003a6600, 0x140006c6ac0, 0x104e472c0)
        /usr/local/go/src/go/types/const.go:239 +0x28
go/types.(*Checker).shift(0x140003a6600, 0x140006c6a00, 0x140006c6ac0, {0x104b8cb98, 0x1400025e3f0}, 0x14)
        /usr/local/go/src/go/types/expr.go:650 +0x1d8
go/types.(*Checker).binary(0x140003a6600, 0x140006c6a00, {0x104b8cb98, 0x1400025e3f0}, {0x104b8d1f8, 0x1400027c5e0}, {0x104b8d168, 0x1400027c600}, 0x14, 0x3873c)
        /usr/local/go/src/go/types/expr.go:796 +0x100
go/types.(*Checker).exprInternal(0x140003a6600, 0x0, 0x140006c6a00, {0x104b8cb98, 0x1400025e3f0}, {0x0, 0x0})
        /usr/local/go/src/go/types/expr.go:1416 +0x1d4
go/types.(*Checker).rawExpr(0x140003a6600, 0x0, 0x140006c6a00, {0x104b8cb98?, 0x1400025e3f0?}, {0x0?, 0x0?}, 0x0)
        /usr/local/go/src/go/types/expr.go:979 +0x12c
go/types.(*Checker).expr(0x140003a6600, 0x104838798?, 0x140006c6a00, {0x104b8cb98?, 0x1400025e3f0?})
        /usr/local/go/src/go/types/expr.go:1513 +0x38
go/types.(*Checker).binary(0x140003a6600, 0x140006c6a00, {0x104b8cb98, 0x1400025e450}, {0x104b8cb98, 0x1400025e3f0}, {0x104b8d1f8, 0x1400027c660}, 0x12, 0x38741)
        /usr/local/go/src/go/types/expr.go:783 +0x70
go/types.(*Checker).exprInternal(0x140003a6600, 0x0, 0x140006c6a00, {0x104b8cb98, 0x1400025e450}, {0x0, 0x0})
        /usr/local/go/src/go/types/expr.go:1416 +0x1d4
go/types.(*Checker).rawExpr(0x140003a6600, 0x0, 0x140006c6a00, {0x104b8cb98?, 0x1400025e450?}, {0x0?, 0x0?}, 0x0)
        /usr/local/go/src/go/types/expr.go:979 +0x12c
go/types.(*Checker).expr(0x140003a6600, 0x104838d10?, 0x140006c6a00, {0x104b8cb98?, 0x1400025e450?})
        /usr/local/go/src/go/types/expr.go:1513 +0x38
go/types.(*Checker).binary(0x140003a6600, 0x140006c6a00, {0x104b8cb98, 0x1400025e480}, {0x104b8cb98, 0x1400025e450}, {0x104b8cc28, 0x1400027c680}, 0xc, 0x38750)
        /usr/local/go/src/go/types/expr.go:783 +0x70
go/types.(*Checker).exprInternal(0x140003a6600, 0x0, 0x140006c6a00, {0x104b8cb98, 0x1400025e480}, {0x0, 0x0})
        /usr/local/go/src/go/types/expr.go:1416 +0x1d4
go/types.(*Checker).rawExpr(0x140003a6600, 0x0, 0x140006c6a00, {0x104b8cb98?, 0x1400025e480?}, {0x0?, 0x0?}, 0x0)
        /usr/local/go/src/go/types/expr.go:979 +0x12c
go/types.(*Checker).expr(0x140003a6600, 0x104e47540?, 0x140006c6a00, {0x104b8cb98?, 0x1400025e480?})
        /usr/local/go/src/go/types/expr.go:1513 +0x38
go/types.(*Checker).initVars(0x140003a6600, {0x140003f40b8, 0x1, 0x1048006a4?}, {0x1400039c1e0, 0x140006c6980?, 0x104b8b920?}, {0x104b8cec8, 0x1400027c6a0?})
        /usr/local/go/src/go/types/assignments.go:381 +0x570
go/types.(*Checker).stmt(0x140003a6600, 0x0, {0x104b8cec8, 0x1400027c6a0})
        /usr/local/go/src/go/types/stmt.go:524 +0x18a4
go/types.(*Checker).stmtList(0x140003a6600, 0x0, {0x1400039c1f0?, 0x1049c3d07?, 0x5?})
        /usr/local/go/src/go/types/stmt.go:121 +0x88
go/types.(*Checker).stmt(0x140003a6600, 0x0, {0x104b8cf58, 0x1400025e4b0})
        /usr/local/go/src/go/types/stmt.go:562 +0x1980
go/types.(*Checker).stmt(0x140003a6600, 0x0, {0x104b8cf88, 0x1400081c240})
        /usr/local/go/src/go/types/stmt.go:574 +0x2598
go/types.(*Checker).stmtList(0x140003a6600, 0x0, {0x1400027c700?, 0x0?, 0x0?})
        /usr/local/go/src/go/types/stmt.go:121 +0x88
go/types.(*Checker).funcBody(0x140003a6600, 0x104b8b920?, {0x1400022a1f0?, 0x104e47540?}, 0x1400091e2c0, 0x1400025e4e0, {0x0?, 0x0?})
        /usr/local/go/src/go/types/stmt.go:41 +0x21c
go/types.(*Checker).funcDecl.func1()
        /usr/local/go/src/go/types/decl.go:852 +0x44
go/types.(*Checker).processDelayed(0x140003a6600, 0x0)
        /usr/local/go/src/go/types/check.go:467 +0x12c
go/types.(*Checker).checkFiles(0x140003a6600, {0x14000260000, 0x1, 0x1})
        /usr/local/go/src/go/types/check.go:411 +0x188
go/types.(*Checker).Files(...)
        /usr/local/go/src/go/types/check.go:372
golang.org/x/tools/go/packages.(*loader).loadPackage(0x140001e4540, 0x140003acae0)
        /Users/joerg.werner/Go/pkg/mod/golang.org/x/tools@v0.9.3/go/packages/packages.go:1055 +0x870
golang.org/x/tools/go/packages.(*loader).loadRecursive.func1()
        /Users/joerg.werner/Go/pkg/mod/golang.org/x/tools@v0.9.3/go/packages/packages.go:854 +0x178
sync.(*Once).doSlow(0x0?, 0x0?)
        /usr/local/go/src/sync/once.go:74 +0x100
sync.(*Once).Do(...)
        /usr/local/go/src/sync/once.go:65
golang.org/x/tools/go/packages.(*loader).loadRecursive(0x0?, 0x0?)
        /Users/joerg.werner/Go/pkg/mod/golang.org/x/tools@v0.9.3/go/packages/packages.go:842 +0x50
golang.org/x/tools/go/packages.(*loader).loadRecursive.func1.1(0x0?)
        /Users/joerg.werner/Go/pkg/mod/golang.org/x/tools@v0.9.3/go/packages/packages.go:849 +0x30
created by golang.org/x/tools/go/packages.(*loader).loadRecursive.func1 in goroutine 150
        /Users/joerg.werner/Go/pkg/mod/golang.org/x/tools@v0.9.3/go/packages/packages.go:848 +0x84
exit status 2

```

**Comment by werjo** [comment] 2024-02-12 21:42
okay now i get it to work too by not using the concrete version for the go run command. 

Can someone explain why it makes a difference if i call 

go run github.com/99designs/gqlgen generate
or 
go run github.com/99designs/gqlgen@latest generate

when both have the same version? Somehow the go run with an explicite version is using older global packages. (v0.9.3 for x/tools in my example). But why?

**Comment by GreenTeaSeb** [comment] 2024-02-13 10:17
It's not a mac only problem, experiencing it on Arch  6.7.4 as well, on the latest go package.
Tried downgrading to 1.21.6, didn't seem to fix it.

**Comment by werjo** [comment] 2024-02-13 12:31
I finally found the root cause of the problem. Its the package golang.org/x/tools. This package is referenced with Version 0.9.3 in gqlgen. But this version is for some reason not working with go1.22. Maybe ist an additional problem with go here, or it was a bug in the tools packages that went unrecognised until go1.22

Updating this lib to a newer one 0.17.0 or 0.18.0 will fix the problem. 

Thats also the problem why `go run github.com/99designs/gqlgen@latest generate` is not working. because the version 0.9.3 is used instead of the module version. 

Thats also why go get -u is fixing the problem for all setups that are using the module version instead of the standalone version.  

So the fix for this problem on this repo is updating the dependencies to newer ones. If that is done `go run github.com/99designs/gqlgen@latest generate` will work again.

**Comment by sonatard** [comment] 2024-02-15 12:45
This issue has been resolved in pull request #2894, but it has not yet been released. If you want to try it, you can use the following command: `go run github.com/99designs/gqlgen@master generate`

@StevenACoffman Do you have any plans for the next release?

**Comment by StevenACoffman** [comment] 2024-02-15 16:20
Hi all! I just put out gqlgen v0.17.44 which should fix this issue. Please open a new issue if after upgrading you are still experiencing an issue.

**Closed by StevenACoffman** 2024-02-15 16:20 UTC

**Comment by zheleznovster** [comment] 2024-04-05 13:08
> 3\. go get -u  github.com/99designs/gqlgen

I only had to do step 3

**Comment by fresonn** [comment] 2024-04-05 16:17
> > 3\. go get -u  github.com/99designs/gqlgen
> 
> I only had to do step 3

Oh really? Yep it's the only thing you should do after maintainer fix in this moment

**Comment by huantt** [comment] 2024-07-30 01:35
My workaround is to use Go 1.21:
```
 GOTOOLCHAIN=go1.21.6 go run github.com/99designs/gqlgen generate 
```
