### ISSUE TITLE
there are no resolvers generated for input 

### ISSUE THREAD

**Issue by FanFani4** [99designs/gqlgen#1948] opened 2022-02-05 10:04 UTC
### What happened?
not generating resolvers for input types ( even with force resolver from gqlgen.yml or @goModel directive )

### What did you expect?
same behavior as for types

### Minimal graphql.schema and models to reproduce
https://github.com/FanFani4/gqlgen-input-bug

### versions
 - `gqlgen version`? 
 - v0.14.0-dev
 - `go version`?
 - go version go1.17.6 linux/amd64
 - dep or go modules?
 - modules

### related issues and discussions
https://github.com/99designs/gqlgen/issues/1307
https://github.com/99designs/gqlgen/discussions/1823

**Comment by FanFani4** [comment] 2022-02-06 10:57
created a PR for this issue , can you accept it pls? 

https://github.com/99designs/gqlgen/pull/1950

**Comment by Omkarz7** [comment] 2022-02-07 12:49
Hey @FanFani4, I am facing the same issue as you. This has led to the following issue in my project
`cannot use resolver (variable of type *graph.Resolver) as generated.ResolverRoot value in struct literal: missing method TestInput`
This has forced me to use **Int** as id datatype.  I am sure not everyone can use this hack. 
I hoping your fix will resolve this issue once merged.

**Comment by frederikhors** [comment] 2022-02-07 13:15
This is very strange. @FanFani4 I can suppose the problem is:

```yml
autobind:
  - "github.com/FanFani4/gqlgen-input-bug/domain"
 ```

Can you please try to generate without these lines?

**Comment by FanFani4** [comment] 2022-02-08 10:25
hi @frederikhors , without binding models it is generating everything fine in graph/model/model_gen.go - 
my point is that if i bind a type - gqlgen is generating a resolver for it in {name}.resolvers.go if it is different from schema but for input it is not. 

this can be reproduced with autobind and manual binding

**Comment by FanFani4** [comment] 2022-02-08 10:32
@Omkarz7 thx, but it is not only about enums , i changed github.com/FanFani4/gqlgen-input-bug TestInput.role in schema  to string and in model to float and the behavior is exactly the same

**Comment by FanFani4** [comment] 2022-02-08 10:39
[plugin/resolvergen/resolver.go](https://github.com/99designs/gqlgen/pull/1950/files#diff-86ed98359ce927135cf803c4ac9d4f5de75a42a54d574971f12e86dfbdef9380)

resolvergen is iterating only through objects only , i added inputs to be iterated as well and resolvers for inputs was generated fine

**Comment by Omkarz7** [comment] 2022-02-08 10:40
@FanFani4 I am not talking about enums, I am talking about TestInput.id, change it to Int and check if that works

`input TestInput {
  id: Int!  #  change from string to int
  role: String!
}`

I got around the issue by accepting id as different parameter in the mutation like this:
`type Mutation {
  foo(id: ID!, in: TestInput!): TestType!
}`

And now I am wondering that we might be talking about two different issues.

**Comment by FanFani4** [comment] 2022-02-08 10:49
> talking about two different issues
yes, i am talking about the case when fields of an input have different types in schema and binded model

**Comment by FanFani4** [comment] 2022-02-13 09:13
hi @frederikhors, any news on this issue ?

**Comment by frederikhors** [comment] 2022-02-13 10:21
Please don't ask for ETA.

**Comment by mojtabacazi** [comment] 2022-02-21 22:47
@FanFani4 is this related to #1868 ?

**Comment by FanFani4** [comment] 2022-02-24 18:02
hi @mojtabacazi , yes it is. you can try to add  this line in your go.mod and try to regenerate the code. just don't forget to remove it when its fixed

```
replace github.com/99designs/gqlgen => github.com/FanFani4/gqlgen v0.16.1-0.20220206105048-15f5c9278130
```

**Closed** 2022-02-25 14:15 UTC
