### ISSUE TITLE
map[string]interface has issue when generating in v0.10.0 or v0.10.1

### ISSUE THREAD

**Issue by imjma** [99designs/gqlgen#878] opened 2019-09-25 06:02 UTC
### What happened?

map[string]interface{} generation issue

`example/todo/generated.go:2938:17: cannot use v (type Test) as type *Test in argument to ec._Test`

### What did you expect?
the error does not happen in v0.9.3

### Minimal graphql.schema and models to reproduce

I just use example/todo to test the map[string]interface{}

add in example/todo/todo.go

`type Test map[string]interface{}`

and add Test type and also add to any existing types, lets say Todo

```
type Todo {
    id: ID!
    text: String!
    done: Boolean! @hasRole(role: OWNER) # only the owner can see if a todo is done
    test: Test
}

type Test {
  key: String
  value: Any
}
```

then add Test into gqlgen.yml

```
 Test:
    model: github.com/99designs/gqlgen/example/todo.Test
```

run `go run github.com/99designs/gqlgen` in example/todo
and then `go run ./example/todo/server/server.go`

### versions
 - `gqlgen version`? v0.10.0 and v0.10.1
 - `go version`? v1.13
 - dep or go modules? modules

**Comment by imjm** [comment] 2019-09-27 01:20
I also try to `map[string]interface{}` in gqlgen.yml, and this error comes

```
generating core failed: field.gotpl: template: field.gotpl:109:51: executing "fieldDefinition" at <.TypeReference.Elem.GO>: nil pointer evaluating *config.TypeReference.GO
```

**Comment by imjm** [comment] 2019-09-27 02:26
could @wabain help have a look? thanks

**Comment by imjm** [comment] 2019-09-27 03:06
it seems this part new code caused issue 

https://github.com/99designs/gqlgen/blob/master/codegen/config/binder.go#L430-L432

**Comment by wabain** [comment] 2019-09-27 04:19
I think the issue is that `Test` is a non-input type. The motivating feature for binding to maps is distinguishing null and missing fields in [changesets](https://gqlgen.com/reference/changesets/) sent from the client. Currently there aren't any tests for binding types occurring in the output to maps.

As of now if you want to manipulate maps in the resolver you can wrap it in a struct — something like:

```go
type Test struct{
    inner: map[string]interface{}
}
```

Currently gqlgen doesn't support automatically resolving fields from map keys, so you would need to implement the resolver code to pull values from the map yourself.

**Comment by imjm** [comment] 2019-09-27 06:40
Thanks @wabain , however, the type changes in go will cause our decode part could not get data for it.

I tried to use "map[string]interface{}" in gqlgen.yml, and codegen throws the error `generating core failed: field.gotpl: template: field.gotpl:109:51: executing "fieldDefinition" at <.TypeReference.Elem.GO>: nil pointer evaluating *config.TypeReference.GO`


modified: example/todo/gqlgen.yml
```
@ example/todo/gqlgen.yml:8 @ models:
    model: # override the default id marshaller to use ints
      - github.com/99designs/gqlgen/graphql.IntID
      - github.com/99designs/gqlgen/graphql.ID
  Test:
    model: "map[string]interface{}"
```

modified: example/todo/schema.graphql
```
@ example/todo/schema.graphql:21 @ type Todo {
    id: ID!
    text: String!
    done: Boolean! @hasRole(role: OWNER) # only the owner can see if a todo is done
    test: Test
}

type Test {
  key: String
  value: Any
}

"Passed to createTodo to create a new todo"
@ example/todo/schema.graphql:47 @ enum Role {
    ADMIN
    OWNER
}

scalar Any
```

**Comment by frederikhors** [comment] 2019-12-17 20:18
@stale please reopen

**Closed** 2020-07-10 05:25 UTC
