### ISSUE TITLE
No data returned if there are errors.

### ISSUE THREAD

**Issue by andrewmunro** [99designs/gqlgen#1191] opened 2020-05-13 08:26 UTC
### What happened?
I have a scenario where I need to return data from a query, but also an error that occured during processing. This _should_ be possible reading the latest version of the spec http://spec.graphql.org/draft/#sel-FAPHRJCAACGyEnlV.

> If the data entry in the response is present (including if it is the value null), the errors entry in the response may contain any errors that occurred during execution. If errors occurred during execution, it should contain those errors.

Currently, if my resolver returns an error (or an error was added using `graphql.AddError`, I see no data back in the response, even if that field is marked as mandatory in the schema. I only get the error back in the response:

```
{
  "errors": [
    {
      "message": "some error occured",
      "path": [
        "todos"
      ]
    }
  ],
  "data": null <--- Should be populated.
}
```

### What did you expect?
I would expect both the data and the errors object to be present.

### Minimal graphql.schema and models to reproduce
Use `go run github.com/99designs/gqlgen init`
Resolver:

```
func (r *queryResolver) Todos(ctx context.Context) ([]Todo, error) {
	return []Todo{
		{ID: "1"},
	}, errors.New("some error occured")
}
```

### versions
 - `gqlgen version`? latest
 - `go version`? go1.14
 - dep or go modules? go modules

**Comment by frederikhors** [comment] 2020-08-11 17:53
Nope

**Comment by sorens** [comment] 2020-09-11 21:10
I have discovered that I am suffering from this issue as well. I 👍 and would love to hear about a possible solution.

**Comment by vhain** [comment] 2020-11-04 12:02
I have found a workaround for now (after skimming through the code base):

```diff
func (r *queryResolver) Todos(ctx context.Context) ([]Todo, error) {
+	graphql.AddErrorf("some error occurred")
	return []Todo{
		{ID: "1"},
-	}, errors.New("some error occurred")
+	}, nil
}
```

Seems like `gqlgen` ignores the returned `data` only if the resolver function directly returns an error, not the ones added via `graphql.AddError*()`.

However I think `gqlgen` should also return `data` even if the resolver returns an error. The fix should also be fairly easy and I am putting up a PR now for maintainers to review.

**Comment by cyberhck** [comment] 2021-03-05 08:53
ahh, just saw this, I also created #1479 I'll close it

**Comment by cyberhck** [comment] 2021-03-05 08:55
in my case, not only this, but let's say I'm querying two things, if one of them returns error with no data, and other one returns the data, then it's still returning null for some reason, look at #1479 for more information

**Comment by ogrok** [comment] 2021-05-05 15:34
Want to add some color to this: say I have an auth directive that throws an error upon failure. It's on some properties but not others, such as:
```
type Thingy {
  firstField: String!
  otherField: String! @auth
```

My intention is for the `firstField` to always be accessible, but if the user requests both fields and auth fails, the entire object returns as null. Now, if I make the `otherField` nullable (`otherField: String @auth`) this doesn't happen anymore and I'd get a response where `firstField: "abc", "otherField": null`.

I guess this is because the `otherField` isn't nullable, but gqlgen wants to return it as null, so the struct is made null rather than the property on the struct?

**Comment by dtrckd** [comment] 2021-12-05 21:37
Hey,

I also encountered the same issue there, also due to some @auth filtering. 

As of gqlgen v0.14, the context need to be passed as follows `graphql.AddErrorf(ctx, "some error occurred")`

**Comment by wilhelmeek** [comment] 2021-12-05 22:45
It appears this is the same issue that https://github.com/99designs/gqlgen/pull/1384 addresses . However I believe this is a misinterpretation of the spec. Specifically referring to the following in http://spec.graphql.org/June2018/#sec-Errors-and-Non-Nullability:

> If an error is thrown while resolving a field, it should be treated as though the field returned null, and an error must be added to the "errors" list in the response.

Marking a field as non-null will result in the null result bubbling up to the nearest nullable ancestor. [See this section of the spec.](http://spec.graphql.org/June2018/#example-90475). @ogrok hopefully this casts some light on your issue.

**Closed by wilhelmeek** 2021-12-05 22:45 UTC

**Comment by gf3** [comment] 2022-01-27 02:42
despite what the spec says, this feature is supported by a handful of popular implementations with the most prominent (and likely most widely used) being Apollo. Apollo allows you to [set an error policy](https://www.apollographql.com/docs/react/data/error-handling/#graphql-error-policies) of `"all"` which enables exactly what is being requested in this issue. i would consider this feature a worthy inclusion into gqlgen (esp. if it's behind a switch) as it unlocks two powerful graphql patterns which are not possible without multiple requests (antithetical to graphql) or a not-insignificant amount of boilerplate (adversarial to your users)

in my experience, two of the core tenets of GraphQL are that it's extensible and it's client-oriented

**Comment by wilhelmeek** [comment] 2022-01-27 04:00
@gf3 I believe that there may be some confusion around the difference between **null** data and **partial** data.

You're correct in saying that Apollo Client will handle **partial** data differently depending on our **client**'s error policy. 

`gqlgen` **absolutely supports** returning partial data, but only if it makes sense (schema-wise) to do so. The following snippet from the docs is a **valid** and **possible** response from a query executed by your `gqlgen` server:
```json
{
  "data": {
    "getInt": 12,
    "getString": null
  },
  "errors": [
    {
      "message": "Failed to get string!",
    }
  ]
}
```

but only assuming that the SDL is defined as:
```graphql
type Query {
  getInt: Number
  getString: String
}
```


**However** if the SDL instead appears as:

```graphql
type Query {
  getInt: Number
  getString: String!
}
```

Then we can expect a response closely resembling:
```json
{
  "data": null,
  "errors": [
    {
      "message": "Failed to get string!",
    }
  ]
}
```

This latter behaviour is what this issue seeks to alter, but I believe that to be an entirely separate concern to handling partial data and client error policies.

Hopefully this clears things up a little!

**Comment by gf3** [comment] 2022-01-27 04:22
@wilhelmeek thank you for responding so quickly, i appreciate the diligence. here's an example from our codebase which becomes much more cumbersome without data + errors—we're providing contextual error information about a field:

### Schema
```graphql
type Order {
  id: ID!
  isCancellable(accountId: ID!): Boolean!
}

type Query {
  order(id: ID!): Order!
}
```

### Query
in our service there are a number of reasons why an order might not be cancellable and in Go this information is propagated through functions as errors. this pattern applies to any sort of field/path validation

```graphql
query {
  order(id: "order-123") {
    id
    isCancellable(accountId: "account-123")
  }
}
```

### Results

**Expected**
```json
{
  "errors": [
    {
      "message": "order contains products that cannot be cancelled",
      "path": [
        "order",
        "isCancellable"
      ]
    }
  ],
  "data": {
    "order": {
      "id": "order-123",
      "isCancellable": false
    }
  }
}
```

**Actual**
```json
{
  "errors": [
    {
      "message": "order contains products that cannot be cancelled",
      "path": [
        "order",
        "isCancellable"
      ]
    }
  ],
  "data": null
}
```

in our actual schema there are multiple fields which provide contextual information this way. note that it would not make sense to make `isCancellable` nullable or anything up the chain. barring the described workaround, the alternative is to wrap types in some sort of failable container which includes the error messages

**Comment by wilhelmeek** [comment] 2022-01-27 04:32
@gf3 no worries! Happy to help 😄 

Why does it not make sense to make `isCancellable` nullable? That would yield exactly the outcome you're after. Obviously things vary from use-case to use-case but it's typically a good idea to rely on nullability for error resilience as well as for maintaining compatibility.

I'm not too familiar with Apollo Server, but would be surprised if they deviate from the spec w.r.t. not bubbling up non-null nulls.

**Comment by gf3** [comment] 2022-01-27 05:01
@wilhelmeek 

> Why does it not make sense to make isCancellable nullable? That would yield exactly the outcome you're after. 

unfortunately (or maybe fortunately) this is only true in JavaScript, in many other languages (including Go) `null`/`nil` is not equivalent to `true` or `false`

for example, a function that implements our `isCancellable` field might look like this:

```go
func IsCancellable(accountID string) bool {
  return true
}

// ...
if IsCancellable("account-123") {
  RefundPayment("order-123")
}
```

to conform to the spec and support nullable fields we need to change our application code to something less idiomatic, and return a pointer to a boolean. 

```go
func IsCancellable(accountID string) *bool {
  b := true
  return &b
}

// ...
canCancel := IsCancellable("account-123")
if canCancel == nil || !(*canCancel) {
  RefundPayment("order-123")
}
```

alternatively we could leave our application code as-is for the most part and do these coercions in the resolvers, however it's just as tedious/unidiomatic and imho defeats the purpose of a code-generating tool like gqlgen

if we don't want to support nullability then we'd need some sort of failable wrapper types which is a lot of boilerplate, e.g.:

```go
func IsCancellable(accountID string) (bool, error) {
  return false, fmt.Errorf("cancellation window passed")
}

type FailableBoolean struct {
  Value  bool
  Errors []error
}

// ...
ok, err := IsCancellable("account-123")
fb := FailableBoolean {
  Value: ok,
  Errors: []error{err},
}
```

**Comment by frederikhors** [comment] 2022-01-28 11:18
@gf3 I think you should open a new RFC-like issue with the current and expected behavior. So let's not lose sight of this situation.

**Comment by gf3** [comment] 2022-01-28 17:59
@frederikhors thanks! i'll open a new issue once i find some spare time
