### ISSUE TITLE
[proposal] Implement batch resolver to handle N+1 problem

### ISSUE THREAD

**Issue by GazeboXu** [99designs/gqlgen#1033] opened 2020-02-16 10:57 UTC
Take the todo example, the root field todos return a Todo list, and in every Todo, the client may request the user field. The current solution to handle the N+1 problem is caching (and intrinsic parallel execution).
the prototype of the resolver is:
```
func (r *todoResolver) User(ctx context.Context, obj *Todo) (*User, error) {
	panic("not implemented")
}
```
please note the obj is a single object.

If it possible to implement a optional BATCH resolver, we can gather the individual calls to todoResolver.User, and then call the batch resolver only once, the batch resolver may look like:
```
func (r *todoResolver) Users(ctx context.Context, objList []*Todo) (map[*Todo]*User, error) {
	panic("not implemented")
}
```
this solution is very appropriate when the resolver itself knows how to implement the batch efficiently, a very common case is database accessing.
I think N `SELECT * FROM user WHERE id = ?` is slower than ONE `SELECT * FROM user WHERE id IN (?)`, right?

So, is it possible to implement an optional batch resolver? although it's non-trivial, but it's a useful feature.

**Comment by BitPhinix** [comment] 2020-02-16 18:20
I don't think it is worth putting directly into gqlgen since there already is a "common" solution for this problem ([Dataloaders](https://gqlgen.com/reference/dataloaders/))

**Comment by GazeboXu** [comment] 2020-02-17 02:50
@BitPhinix , thanks for your comment.
Yes, there is Dataloader(dataloaden in gqlgen), but this solution is not very intuitional, it involves more timers, lockers. Especially the waiting time is very tricky. And more generated code, more manpower .
But batch resolver is a NORMAL way to handle this(no more lockers and tricky waiting time), and it should be an optional resolver, so compatibility is not a problem.
I do think it's a special feature compare to other GraphQL implementation. 
Actually, I am not an expert for GraphQL, is it possible to implement such a feature. If yes, is it difficult to implement it in gqlgen?

**Comment by vektah** [comment] 2020-02-18 02:32
dupe of https://github.com/99designs/gqlgen/issues/518

**Closed by vektah** 2020-02-18 02:32 UTC
Labels: enhancement
