### ISSUE TITLE
Gateway for remote schemas

### ISSUE THREAD

**Issue by frederikhors** [99designs/gqlgen#975] opened 2020-01-06 12:19 UTC
Is there a desire to also generate a gateway for remote schemas?

Apollo federation or not, like https://github.com/nautilus/gateway ?

**Comment by remorses** [comment] 2020-01-31 18:45
Very interested, the only solution now for Apollo Federation is using something in nodejs, it colpletely kills performance

**Comment by vektah** [comment] 2020-02-05 12:04
dupe of https://github.com/99designs/gqlgen/issues/5

**Closed by vektah** 2020-02-05 12:04 UTC
