### ISSUE TITLE
error while running go generate

### ISSUE THREAD

**Issue by shimish2** [99designs/gqlgen#2211] opened 2022-05-26 05:20 UTC
### What happened?

I am getting error while running go generate 

```ec._fieldMiddleware undefined (type *executionContext has no field or method _fieldMiddleware)```

### What did you expect?
go generate should run successfully. After downgrading gqlgen to v1.14.0 & gqlparser to v2.2.0, go generate was successful.

### versions
 - `go run github.com/99designs/gqlgen version`?
      v0.17.8
 - `go version`?
      1.18

**Comment by frederikhors** [comment] 2022-05-26 08:15
Please create a reproduction repo.

**Comment by shimish2** [comment] 2022-05-26 17:38
Please checkout this changes and try to run ```go generate``` from search directory.

**Comment by frederikhors** [comment] 2022-05-27 12:59
Can you try with 0.17.9, please?

**Comment by shimish2** [comment] 2022-05-27 17:03
tried with 0.17.9 and got same error.

**Comment by ashishb** [comment] 2022-06-01 02:11
Same issue

**Comment by andaaron** [comment] 2022-07-15 09:20
Hi,
Looks like sticking to the v0.14.0 workaround is not working with Go 1.18 (works with 1.17).
Do we have a long term solution?

**Comment by manisharma** [comment] 2022-07-26 12:35
any updates here ? `go run github.com/99designs/gqlgen generate` still fails
```shell
$ go version
go version go1.18 darwin/arm64
```

**Comment by andaaron** [comment] 2022-07-26 17:03
For our project we started from scratch with `gqlgen init`, replaced the schema with ours, and did some code refactoring to move our resolvers to match the new file/folder structure (before this we did not have a gqlgen.yml, or a schema.resolvers.go file - the methods in schema.resolvers.go were implemented in resolvers.go).

Currently it's working with latest gqlgen and go1.18.

**Comment by frederikhors** [comment] 2022-07-26 17:07
This is not a problem anymore with gqlgen latest versions and Go 1.16.x, 1.17.x, 1.18x.

Maybe you can use `gqlgen init` from scratch in a new dir and notice the differences from your project.

Or you can re-check re-reading the config page.

Definitely this is not something wrong with latest versions, hence I'm closing this.

**Closed by frederikhors** 2022-07-26 17:07 UTC

**Comment by andrey-bobryshev-90poe** [comment] 2022-08-12 11:39
I found the cause of this issue. If you running generate with no `gqlgen.yml` file you will be getting this error because generated code will contain this piece of code:
```
	resTmp := ec._fieldMiddleware(ctx, obj, func(rctx context.Context) (interface{}, error) {
		ctx = rctx // use context from middleware stack in children
		return obj.ID, nil
	})
```
This is where it comes from https://github.com/99designs/gqlgen/blob/6855b7290cab62a1fc6a26a2b633e0b5bbf248da/codegen/field.gotpl#L19-L23
Once you add `gqlgen.yml` everything works well.
Probably `$.AllDirectives.LocationDirectives` var initialises wrong without config file.
