### ISSUE TITLE
Null bubbles up to non-nullable array element

### ISSUE THREAD

**Issue by edsrzf** [99designs/gqlgen#811] opened 2019-07-30 10:05 UTC
### What happened?

I've defined a field in my schema that is an array of non-null elements (`[T!]!`). When an error occurs resolving one of the elements of the array, the null bubbles up to the element of the array rather than the next nullable field.

### What did you expect?

Non-nullable elements should never be null. I expect the null to bubble up to the next nullable field, as [defined in the specification](https://graphql.github.io/graphql-spec/June2018/#sec-Errors).

### Minimal graphql.schema and models to reproduce

There's a full repo with instructions here: https://github.com/edsrzf/gqlgen-null-repro

Schema:

```graphql
type Todo {
  user: User!
}

type User {
  name: String!
}

type Query {
  todos: [Todo!]!
}
```

Resolvers:

```go
package gqlgen_repro

import (
	"context"
	"errors"
)

type Resolver struct{}

func (r *Resolver) Query() QueryResolver {
	return &queryResolver{r}
}

func (r *Resolver) Todo() TodoResolver {
	return &todoResolver{r}
}

type queryResolver struct{ *Resolver }

func (r *queryResolver) Todos(ctx context.Context) ([]*Todo, error) {
	return []*Todo{{}}, nil
}

type todoResolver struct{ *Resolver }

func (r *todoResolver) User(ctx context.Context, obj *Todo) (*User, error) {
	return nil, errors.New("oh no")
}
```

I used the models generated by gqlgen, but forced `Todo.user` to use a resolver.

### versions
 - `gqlgen version`? `0.9.1`
 - `go version`? `1.12.6`
 - dep or go modules? Go modules

**Comment by DouglasHoang** [comment] 2019-11-05 20:40
It looks like when you use this
`
query {
todos: [Todo]!
}
`
You get 
`func (r *queryResolver) Todos(ctx context.Context) ([]Todo, error) {
	return []Todo{{}}, nil
}`
It looks like they are mixed up

**Comment by vvakame** [comment] 2019-12-25 07:18
I confirmed this issue still occurred in v0.10.2 and master/HEAD (`v0.10.3-0.20191128123652-f869f5a85385`)

**Comment by NaLLiFFuNT** [comment] 2021-03-03 20:24
any updates?

**Comment by wilhelmeek** [comment] 2021-03-09 22:36
I've raised a PR that addresses this behaviour here https://github.com/99designs/gqlgen/pull/1480. Not sure who the best people to loop in are though?

**Comment by wilhelmeek** [comment] 2021-03-12 04:27
The above PR's been merged, so this issue should now be resolved.

**Comment by arash16** [comment] 2021-08-18 22:13
So is there going to be a new patch release? It's been months past by?!

**Closed** 2021-09-17 02:34 UTC
Labels: bug, accepted
