### ISSUE TITLE
Embedded structs result in nil pointer dereference

### ISSUE THREAD

**Issue by fridolin-koch** [99designs/gqlgen#590] opened 2019-03-06 14:22 UTC
### Expected Behaviour

Using embedded structs from another package should be working like in 0.7

```go
import "github.com/acme/project/cms/model"

type Category struct {
	*model.Category
}

func (c *Category) IsNode() {}
```

Config

```yaml
models:
  Category:
    model: github.com/acme/project/cms/graph.Category
```

### Actual Behavior

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb0 pc=0x1300b61]

goroutine 1 [running]:
github.com/acme/project/vendor/github.com/99designs/gqlgen/codegen/config.(*Binder).ObjectPosition(0xc000b5ee00, 0x16e1860, 0xc000a8cb90, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/frido/Go/src/github.com/acme/project/vendor/github.com/99designs/gqlgen/codegen/config/binder.go:65 +0x261
github.com/acme/project/vendor/github.com/99designs/gqlgen/codegen.(*builder).bindField(0xc000735900, 0xc000116900, 0xc000bd2120, 0x0, 0x0)
        /Users/frido/Go/src/github.com/acme/project/vendor/github.com/99designs/gqlgen/codegen/field.go:115 +0x3b8
github.com/acme/project/vendor/github.com/99designs/gqlgen/codegen.(*builder).buildField(0xc000735900, 0xc000116900, 0xc000c3fc00, 0x0, 0x1, 0xc0000b75b8)
        /Users/frido/Go/src/github.com/acme/project/vendor/github.com/99designs/gqlgen/codegen/field.go:64 +0x31d
github.com/acme/project/vendor/github.com/99designs/gqlgen/codegen.(*builder).buildObject(0xc000735900, 0xc000871980, 0x15f02e8, 0x6, 0x0)
        /Users/frido/Go/src/github.com/acme/project/vendor/github.com/99designs/gqlgen/codegen/object.go:72 +0x4d4
github.com/acme/project/vendor/github.com/99designs/gqlgen/codegen.BuildData(0xc0002100c0, 0x16ccfa0, 0x1adb460, 0x0)
        /Users/frido/Go/src/github.com/acme/project/vendor/github.com/99designs/gqlgen/codegen/data.go:83 +0x47f
github.com/acme/project/vendor/github.com/99designs/gqlgen/api.Generate(0xc0002100c0, 0x0, 0x0, 0x0, 0x0, 0x1631038)
        /Users/frido/Go/src/github.com/acme/project/vendor/github.com/99designs/gqlgen/api/generate.go:37 +0x22d
github.com/acme/project/vendor/github.com/99designs/gqlgen/cmd.glob..func1(0xc000218000)
        /Users/frido/Go/src/github.com/acme/project/vendor/github.com/99designs/gqlgen/cmd/gen.go:39 +0xa2
github.com/acme/project/vendor/github.com/urfave/cli.HandleAction(0x152f7e0, 0x16301a8, 0xc000218000, 0xc0001322a0, 0x0)
        /Users/frido/Go/src/github.com/acme/project/vendor/github.com/urfave/cli/app.go:492 +0x7c
github.com/acme/project/vendor/github.com/urfave/cli.(*App).Run(0xc0000ac1a0, 0xc00000e080, 0x2, 0x2, 0x0, 0x0)
        /Users/frido/Go/src/github.com/acme/project/vendor/github.com/urfave/cli/app.go:264 +0x57c
github.com/acme/project/vendor/github.com/99designs/gqlgen/cmd.Execute()
        /Users/frido/Go/src/github.com/acme/project/vendor/github.com/99designs/gqlgen/cmd/root.go:40 +0x224
main.main()
        /Users/frido/Go/src/github.com/acme/project/cms/graph/schema/gqlgen.go:8 +0x20
exit status 2
resolver.go:23: running "go": exit status 1
make: *** [gqlgen] Error 1
```

As far as I traced back the error, the problem is that the embedded struct is not present in the TypeMap.

As I workaround I added some random struct from the package to the config

```yaml
models:
  SomeDummy:
    model: github.com/acme/project/cms/model.TableNames
```

### Minimal graphql.schema and models to reproduce

Best regards,
Frido

**Comment by vektah** [comment] 2019-03-06 23:10
dupe of https://github.com/99designs/gqlgen/issues/363

**Closed by vektah** 2019-03-06 23:10 UTC
Labels: bug
