### ISSUE TITLE
Is this project currently being discontinued?

### ISSUE THREAD

**Issue by frederikhors** [99designs/gqlgen#1386] opened 2020-11-05 18:41 UTC
I have a great concern in my heart: that sooner or later this majestic project will be archived. 😢

As it is currently in use in several of my projects I ask you with my heart in my hands and hope in my eyes: **is this project currently being discontinued or is it active and maintained?**

Every day I read several unanswered questions and many useful PRs that have been stuck for a long time: I'm really afraid.

Thanks for your answer.

**Comment by warent** [comment] 2020-11-05 21:02
It is unfortunate that this repo seems to have been abandoned. I'm using it in production and it works great. There are so many people that actively use this and it's so important to app development I'm confident that we could fork the repo if necessary.

**Comment by ahummel25** [comment] 2020-11-09 21:40
I see there are still commits and merges happening. Possible it's just a small number of maintainers on this repo who are maybe overwhelmed by the number of open issues?

**Comment by austincollinpena** [comment] 2020-11-11 03:03
Yeah it works great for me, but the fact that it's not maintained is concerning. I would love a project update from maintainers.

**Comment by mtibben** [comment] 2020-11-12 09:03
> is this project currently being discontinued or is it active and maintained?

Hey @frederikhors, almost 100 PRs have been merged this year alone. It depends on your definition of "maintained"!

> Possible it's just a small number of maintainers on this repo who are maybe overwhelmed by the number of open issues?

Yeah that's the case @warent

> Perhaps there are some politics at play?

No politics, just limited time.

> I'm unsure what 99designs needs out of the repo, and it was created, AFAIK, by them for them

That's correct @austincollinpena - this GraphQL server drives 99designs.com

---
Folks, this is open source and we'd be glad to hear of anyone willing to pitch in and help in any way. The simplest way you could start contributing immediately
 - replying and helping resolve the many issues that get created every week
 - reviewing code

@vektah has been the primary author/maintainer but he hasn't had a huge focus on this recently. That's OK. This library does the job for 99designs, and we're glad it also helps so many other people and use-cases.

**Closed** 2020-11-12 10:04 UTC

**Comment by austincollinpena** [comment] 2020-11-13 18:48
@mtibben How would you feel about a priority system to help newcomers contribute with a strong call to action at the top of the repo?

**Comment by hi019** [comment] 2020-11-27 18:56
@mtibben Maybe we could reserve Issues for reproducible bug reports only, and questions could use [Github Discussions](https://github.com/tannerlinsley/react-query/discussions)? There also seem to be quite a few Issues that are resolved but not closed. I could help you close some of those if you would like.

**Comment by mtibben** [comment] 2020-11-30 06:06
Thanks for the tip @hi019 I've [requested access to the beta](https://github.community/t/can-one-apply-for-github-discussions-beta/121120/502) 🤞

**Comment by ipfans** [comment] 2021-04-24 05:50
@mtibben Github Discussions seems to be public. So can gqlgen project setup a discussion?
